In [1]:

import pandas as pd
import sqlite3

conn = sqlite3.connect('hospital_readmissions.db')

In [4]:
import os
os.listdir('data/raw/')

['FY_2026_Hospital_Readmissions_Reduction_Program_Hospital.csv',
 '.DS_Store',
 'Unplanned_Hospital_Visits-Hospital.csv',
 'Hospital_General_Information.csv']

In [5]:
#  CSVs into sqlite
df1 = pd.read_csv('data/raw/Hospital_General_Information.csv', dtype=str)
df1.to_sql('raw_hospital_info', conn, if_exists='replace', index=False)

df2 = pd.read_csv('data/raw/FY_2026_Hospital_Readmissions_Reduction_Program_Hospital.csv', dtype=str)
df2.to_sql('raw_hrrp', conn, if_exists='replace', index=False)

df3 = pd.read_csv('data/raw/Unplanned_Hospital_Visits-Hospital.csv', dtype=str)
df3.to_sql('raw_unplanned_visits', conn, if_exists='replace', index=False)

67046

In [6]:
# now you can run SQL directly in the notebook
pd.read_sql("SELECT * FROM raw_hospital_info LIMIT 5", conn)

,Facility ID,Facility Name,Address,City/Town,State,ZIP Code,County/Parish,Telephone Number,Hospital Type,Hospital Ownership,...,Count of READM Measures Better,Count of READM Measures No Different,Count of READM Measures Worse,READM Group Footnote,Pt Exp Group Measure Count,Count of Facility Pt Exp Measures,Pt Exp Group Footnote,TE Group Measure Count,Count of Facility TE Measures,TE Group Footnote
0,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,Acute Care Hospitals,Government - Hospital District or Authority,...,0,11,0,None,8,8,None,12,11,None
1,010005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,(256) 593-8310,Acute Care Hospitals,Government - Hospital District or Authority,...,0,8,1,None,8,8,None,12,12,None
2,010006,NORTH ALABAMA MEDICAL CENTER,1701 VETERANS DRIVE,FLORENCE,AL,35630,LAUDERDALE,(256) 768-8400,Acute Care Hospitals,Proprietary,...,0,8,1,None,8,8,None,12,10,None
3,010007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,(334) 493-3541,Acute Care Hospitals,Voluntary non-profit - Private,...,0,7,0,None,8,8,None,12,7,None
4,010008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,(334) 335-3374,Acute Care Hospitals,Proprietary,...,0,2,0,None,8,Not Available,5,12,6,None

In [7]:
pd.read_sql("SELECT * FROM raw_hrrp LIMIT 5", conn)

,Facility Name,Facility ID,State,Measure Name,Number of Discharges,Footnote,Excess Readmission Ratio,Predicted Readmission Rate,Expected Readmission Rate,Number of Readmissions,Start Date,End Date
0,SOUTHEAST HEALTH MEDICAL CENTER,010001,AL,READM-30-HIP-KNEE-HRRP,None,None,0.9875,4.5734,4.6311,Too Few to Report,07/01/2021,06/30/2024
1,SOUTHEAST HEALTH MEDICAL CENTER,010001,AL,READM-30-CABG-HRRP,137,None,0.9531,10.3960,10.9078,13,07/01/2021,06/30/2024
2,SOUTHEAST HEALTH MEDICAL CENTER,010001,AL,READM-30-AMI-HRRP,273,None,0.9370,13.2998,14.1948,33,07/01/2021,06/30/2024
3,SOUTHEAST HEALTH MEDICAL CENTER,010001,AL,READM-30-COPD-HRRP,122,None,0.9823,16.6384,16.9389,19,07/01/2021,06/30/2024
4,SOUTHEAST HEALTH MEDICAL CENTER,010001,AL,READM-30-PN-HRRP,507,None,0.9871,15.7529,15.9591,79,07/01/2021,06/30/2024

In [8]:
pd.read_sql("SELECT * FROM raw_unplanned_visits LIMIT 5", conn)

,Facility ID,Facility Name,Address,City/Town,State,ZIP Code,County/Parish,Telephone Number,Measure ID,Measure Name,Compared to National,Denominator,Score,Lower Estimate,Higher Estimate,Number of Patients,Number of Patients Returned,Footnote,Start Date,End Date
0,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,EDAC_30_AMI,Hospital return days for heart attack patients,Fewer Days Than Average per 100 Discharges,273,-15.6,-25.9,-4.2,264,68,None,07/01/2021,06/30/2024
1,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,EDAC_30_HF,Hospital return days for heart failure patients,Average Days per 100 Discharges,652,-1.1,-10,7.9,541,186,None,07/01/2021,06/30/2024
2,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,EDAC_30_PN,Hospital return days for pneumonia patients,More Days Than Average per 100 Discharges,507,17.4,8.2,27.5,471,114,None,07/01/2021,06/30/2024
3,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,Hybrid_HWR,Hybrid Hospital-Wide All-Cause Readmission Mea...,No Different Than the National Rate,2824,15.1,13.2,17.2,Not Applicable,Not Applicable,None,07/01/2023,06/30/2024
4,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,OP_32,Rate of unplanned hospital visits after colono...,No Different Than the National Rate,234,12.7,9.5,17,Not Applicable,Not Applicable,None,01/01/2022,12/31/2024

In [9]:
pd.read_sql("SELECT * FROM raw_hrrp LIMIT 5", conn)

,Facility Name,Facility ID,State,Measure Name,Number of Discharges,Footnote,Excess Readmission Ratio,Predicted Readmission Rate,Expected Readmission Rate,Number of Readmissions,Start Date,End Date
0,SOUTHEAST HEALTH MEDICAL CENTER,010001,AL,READM-30-HIP-KNEE-HRRP,None,None,0.9875,4.5734,4.6311,Too Few to Report,07/01/2021,06/30/2024
1,SOUTHEAST HEALTH MEDICAL CENTER,010001,AL,READM-30-CABG-HRRP,137,None,0.9531,10.3960,10.9078,13,07/01/2021,06/30/2024
2,SOUTHEAST HEALTH MEDICAL CENTER,010001,AL,READM-30-AMI-HRRP,273,None,0.9370,13.2998,14.1948,33,07/01/2021,06/30/2024
3,SOUTHEAST HEALTH MEDICAL CENTER,010001,AL,READM-30-COPD-HRRP,122,None,0.9823,16.6384,16.9389,19,07/01/2021,06/30/2024
4,SOUTHEAST HEALTH MEDICAL CENTER,010001,AL,READM-30-PN-HRRP,507,None,0.9871,15.7529,15.9591,79,07/01/2021,06/30/2024

In [10]:
#unplanned visit files
pd.read_sql("""
    SELECT [Measure ID], COUNT(*) as cnt 
    FROM raw_unplanned_visits 
    GROUP BY [Measure ID]
""", conn)

           Measure ID   cnt
0         EDAC_30_AMI  4789
1          EDAC_30_HF  4789
2          EDAC_30_PN  4789
3          Hybrid_HWR  4789
4               OP_32  4789
5           OP_35_ADM  4789
6            OP_35_ED  4789
7               OP_36  4789
8        READM_30_AMI  4789
9       READM_30_CABG  4789
10      READM_30_COPD  4789
11        READM_30_HF  4789
12  READM_30_HIP_KNEE  4789
13        READM_30_PN  4789

In [11]:
pd.read_sql("PRAGMA table_info(raw_hrrp)", conn)

    cid                        name  type  notnull dflt_value  pk
0     0               Facility Name  TEXT        0       None   0
1     1                 Facility ID  TEXT        0       None   0
2     2                       State  TEXT        0       None   0
3     3                Measure Name  TEXT        0       None   0
4     4        Number of Discharges  TEXT        0       None   0
5     5                    Footnote  TEXT        0       None   0
6     6    Excess Readmission Ratio  TEXT        0       None   0
7     7  Predicted Readmission Rate  TEXT        0       None   0
8     8   Expected Readmission Rate  TEXT        0       None   0
9     9      Number of Readmissions  TEXT        0       None   0
10   10                  Start Date  TEXT        0       None   0
11   11                    End Date  TEXT        0       None   0

In [12]:
pd.read_sql("PRAGMA table_info(raw_unplanned_visits)", conn)

    cid                         name  type  notnull dflt_value  pk
0     0                  Facility ID  TEXT        0       None   0
1     1                Facility Name  TEXT        0       None   0
2     2                      Address  TEXT        0       None   0
3     3                    City/Town  TEXT        0       None   0
4     4                        State  TEXT        0       None   0
5     5                     ZIP Code  TEXT        0       None   0
6     6                County/Parish  TEXT        0       None   0
7     7             Telephone Number  TEXT        0       None   0
8     8                   Measure ID  TEXT        0       None   0
9     9                 Measure Name  TEXT        0       None   0
10   10         Compared to National  TEXT        0       None   0
11   11                  Denominator  TEXT        0       None   0
12   12                        Score  TEXT        0       None   0
13   13               Lower Estimate  TEXT        0       None   0
14   14              Higher Estimate  TEXT        0       None   0
15   15           Number of Patients  TEXT        0       None   0
16   16  Number of Patients Returned  TEXT        0       None   0
17   17                     Footnote  TEXT        0       None   0
18   18                   Start Date  TEXT        0       None   0
19   19                     End Date  TEXT        0       None   0

In [13]:
#  messy values in HRRP
pd.read_sql("""
    SELECT [Excess Readmission Ratio], COUNT(*) as cnt
    FROM raw_hrrp
    WHERE [Excess Readmission Ratio] IS NULL 
       OR [Excess Readmission Ratio] = 'Not Available'
       OR [Excess Readmission Ratio] = ''
    GROUP BY [Excess Readmission Ratio]
""", conn)

  Excess Readmission Ratio   cnt
0                     None  6610

In [14]:
# unplanned visits for messy Score values
pd.read_sql("""
    SELECT Score, COUNT(*) as cnt
    FROM raw_unplanned_visits
    WHERE Score = 'Not Available' 
       OR Score = 'Too Few to Report'
       OR Score IS NULL
    GROUP BY Score
""", conn)

           Score    cnt
0  Not Available  31766

In [15]:
pd.read_sql("""
    SELECT 'hospital_info' as tbl, COUNT(DISTINCT [Facility ID]) as cnt FROM raw_hospital_info
    UNION ALL
    SELECT 'hrrp', COUNT(DISTINCT [Facility ID]) FROM raw_hrrp
    UNION ALL
    SELECT 'unplanned_visits', COUNT(DISTINCT [Facility ID]) FROM raw_unplanned_visits
""", conn)

                tbl   cnt
0     hospital_info  5426
1              hrrp  3055
2  unplanned_visits  4789

In [16]:
pd.read_sql("""
    SELECT [Measure ID],
           COUNT(*) as total,
           SUM(CASE WHEN Score != 'Not Available' AND Score IS NOT NULL THEN 1 ELSE 0 END) as has_data,
           SUM(CASE WHEN Score = 'Not Available' OR Score IS NULL THEN 1 ELSE 0 END) as missing
    FROM raw_unplanned_visits
    WHERE [Measure ID] LIKE 'READM_30%'
    GROUP BY [Measure ID]
""", conn)

          Measure ID  total  has_data  missing
0       READM_30_AMI   4789      1825     2964
1      READM_30_CABG   4789       878     3911
2      READM_30_COPD   4789      2699     2090
3        READM_30_HF   4789      3155     1634
4  READM_30_HIP_KNEE   4789      1625     3164
5        READM_30_PN   4789      3638     1151